import { tv } from "tailwind-variants";

export const titleScreen = tv({
	slots: {
		container: [
			"bg-black",
			"h-screen",
			"w-screen",
			"font-sans",
			"text-white",
			"overflow-hidden",
			"flex",
			"items-center",
			"justify-center",
			"p-4",
			"md:p-8",
		],
		titleGrid: [
			"grid",
			"grid-cols-1 md:grid-cols-2",
			"gap-6",
			"w-full",
			"max-w-6xl",
		],
		menuBox: [
			"border-[6px]",
			"border-[#FF4444]",
			"bg-black",
			"p-6",
			"flex",
			"flex-col",
			"justify-start",
			"min-h-[300px]",
		],
		menuItem: [
			"text-2xl",
			"font-bold",
			"py-2",
			"px-2",
			"mb-1",
			"cursor-pointer",
			"transition-all",
			"duration-200",
			"uppercase",
			"tracking-[0.3em]",
			"text-white",
			"border-2",
			"border-transparent",
			"hover:border-[#FF4444]",
		],
		menuItemSelected: ["bg-[#FF4444]", "text-white", "border-[#FF4444]"],
		menuItemDisabled: [
			"text-gray-600",
			"cursor-not-allowed",
			"border-transparent",
			"hover:border-transparent",
		],
		visualBox: [
			"bg-black",
			"flex",
			"items-center",
			"justify-center",
			"min-h-[350px]",
			"p-8",
			"relative",
			"overflow-hidden",
			"w-full",
		],
		infoBox: [
			"col-span-1 md:col-span-2",
			"border-[6px]",
			"border-[#FF4444]",
			"bg-black",
			"p-8",
			"min-h-[150px]",
			"flex",
			"items-center",
			"justify-center",
			"text-center",
		],
		subtitle: ["text-xl", "text-[#44FFFF]", "font-bold", "tracking-[0.5em]"],
		playerListWrapper: ["mt-8", "text-left", "w-full"],
		playerItem: [
			"flex",
			"justify-between",
			"text-lg",
			"mb-1",
			"font-bold",
			"tracking-wider",
		],
		rankingText: ["mr-6", "text-[#44FFFF]", "font-sans", "text-base"],
		playerName: "[color:var(--player-name-color)]",
		playerStatus: "font-black text-sm [color:var(--player-status-color)]",
		aboutScrollArea:
			"overflow-y-auto p-6 custom-scrollbar flex-1 [scrollbar-width:thin] [scrollbar-color:#FF4444_#000]",
	},
});
