import { tv } from 'tailwind-variants'

export const lpPage = tv({
    slots: {
        main: 'min-h-screen relative overflow-hidden',
        contentWrapper: 'relative z-10 flex flex-col items-center',
        sectionDivider: 'w-full max-w-5xl px-8',
        dividerRow: 'flex items-center gap-4 mb-4',
        dividerLine: 'h-px flex-1 bg-linear-to-r from-transparent via-brand-500/40 to-transparent',
        dividerLabel: 'text-[10px] tracking-[0.4em] text-brand-600 uppercase font-dot-gothic-16',
        dividerSub: 'text-center text-[11px] text-brand-700 mt-1 font-dot-gothic-16',
        gamesSection: 'w-full max-w-5xl px-8 py-8 space-y-24',
        gameEntry: 'group',
        gameBanner: 'flex items-center gap-4 mb-6',
        gameNumber: 'text-[80px] font-black leading-none select-none font-rubik-puddles',
        gameTags: 'flex gap-2 mb-2 flex-wrap',
        gameTitle: 'text-4xl font-black font-rubik-puddles',
        gameCard: 'glass-card rounded-2xl overflow-hidden transition-all duration-500',
        gameCardHeader: 'flex flex-col md:flex-row gap-6 items-start p-8 pb-4',
        gameDescription: 'flex-1 text-brand-700 text-sm leading-relaxed font-dot-gothic-16',
        gameDeveloper: 'flex items-center gap-3 px-4 py-3 rounded-xl shrink-0',
        devAvatar: 'relative w-10 h-10',
        devComment: 'text-xs text-brand-800 font-cherry-bomb-one',
        gameDemoWrapper: 'mx-8 mb-8 rounded-xl overflow-hidden',
        ctaSection: 'py-24 px-8 w-full max-w-2xl',
        ctaInner: 'relative text-center',
        ctaAurora: 'absolute -inset-12 opacity-20 pointer-events-none',
        ctaReadyLabel: 'text-brand-600 text-[10px] tracking-[0.4em] uppercase mb-6 font-dot-gothic-16',
        ctaHeading: 'text-5xl md:text-6xl leading-snug mb-2 font-cherry-bomb-one',
        ctaHeadingSpan: 'bg-[linear-gradient(135deg,#e0e7ff,#a5b4fc,#c084fc)] bg-clip-text text-transparent',
        ctaButton: [
            'group inline-flex items-center gap-2.5 px-8 py-3.5 rounded-full',
            'text-sm font-semibold tracking-wider text-white font-dot-gothic-16',
            'transition-all duration-300 hover:scale-105',
            'bg-[linear-gradient(135deg,rgba(99,102,241,0.15),rgba(168,85,247,0.15))]',
            'border border-brand-500/40',
            'shadow-[inset_0_1px_0_rgba(255,255,255,0.08)]',
            'hover:shadow-[0_0_24px_rgba(129,140,248,0.25),inset_0_1px_0_rgba(255,255,255,0.08)]',
            'hover:border-brand-500/70',
        ],
        ctaPulse: 'w-1.5 h-1.5 rounded-full bg-brand-400 animate-pulse',
        ctaArrow: 'w-3.5 h-3.5 opacity-50 group-hover:opacity-100 group-hover:translate-x-0.5 transition-all',
        ctaFreeLabel: 'mt-6 text-[10px] text-brand-600 font-dot-gothic-16',
        ctaLegal: 'mt-3 text-[11px] text-brand-700/60 font-dot-gothic-16',
        ctaLegalLink: 'hover:text-brand-500 transition-colors',
        footer: 'pb-12 text-center space-y-2',
        footerTitle: 'text-brand-500 font-bold tracking-widest font-rubik-puddles',
        footerSub: 'text-xs text-brand-700 opacity-60 font-dot-gothic-16',
    },
})
